### ISSUE TITLE
curl: (1) Protocol "https" not supported or disabled in libcurl on suse x64 platform

### ISSUE THREAD

**Issue by BhaskarShiv** [onelogin/python-saml#243]
Hello All,
I am facing an error "curl: (1) Protocol "https" not supported or disabled in libcurl on suse x64 platform"
when i POST a request to a https url on suse x64 machine.

I have used/tried all libcurl version 7.63.0, 7.62.0, 7.61.1, 7.61.0, 7.60.0, 7.59.0, 7.58.0 build with openssl version 1.1.1a and 1.1.1.

I didn't face any compilation errors and build(make) was successful with all of the above combinations.

Below are the compilation steps i have followed,
suse1164> echo $PKG_CONFIG_PATH
/apps/clp/_dependencies/openssl/openssl1.1.1a/lib64/pkgconfig

suse1164> echo $LDFLAGS
-L/apps/clp/_dependencies/openssl/openssl1.1.1a/lib64/

./configure --with-ssl=/apps/clp/_dependencies/openssl/openssl1.1.1a
make

Below is compilation details,
suse1164> curl -V
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0
Release-Date: 2018-12-12
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp
Features: AsynchDNS Largefile UnixSockets

suse1164 > curl --version | grep Protocols
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp

suse1164-clpadmin > which curl
./curl                                   /* current directory of insatlled version */

NOTE : when i use curl google.com is working fine, but when i use "https" i am facing issues as shown below.  But then with "http" is working fine. There are no single/double quotes given for the url and No spaces are also found.

suse1164 > curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

suse1164> curl https://www.google.com
curl: (1) Protocol "https" not supported or disabled in libcurl

NOTE for http is working fine  -> clpsuse1164> curl http://www.google.com

My samples are failing with https NOT supporting/disabled issue.
 
Please help me fixing this issue. Your help is higly appreciated. 

Thanks,
Bhaskar

**Comment by BhaskarShiv** [comment]
Hi, can someone help me fixing this issue.

**Comment by pitbulk** [comment]
Sorry but I don't see how is that related to the python-saml project.
